# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='lnglat',
        ),
    ]
