# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 16:48
from __future__ import unicode_literals

import blog.fields
import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160728_0723'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=20)),
                ('post_code', blog.fields.PostCodeField(max_length=10, validators=[blog.validators.post_code_validator, blog.validators.post_code_validator, blog.validators.post_code_validator])),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=blog.fields.PhoneNumberField(max_length=20, validators=[blog.validators.phone_number_validator, blog.validators.phone_number_validator, blog.validators.phone_number_validator]),
        ),
    ]
