# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-06 13:25
from __future__ import unicode_literals

import blog.fields
import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20160803_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=blog.fields.PhoneNumberField(max_length=20, validators=[blog.validators.phone_number_validator, blog.validators.phone_number_validator, blog.validators.phone_number_validator]),
        ),
        migrations.AlterField(
            model_name='postcode',
            name='post_code',
            field=blog.fields.PostCodeField(max_length=10, validators=[blog.validators.post_code_validator, blog.validators.post_code_validator, blog.validators.post_code_validator]),
        ),
    ]
